name: Build update executable

on:
  push:
    branches: [ senpai ]
  pull_request:
    branches: [ senpai ]

jobs:

  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install MinGW-w64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Download Sun Build System
      uses: actions/download-artifact@v3
      with:
        name: sun-release
        repo: calamity-inc/Sun # Replace with the repository containing the Sun release
        path: sun # Optional, specifies the directory to download the artifact to
        
    - name: Compile C++ Program
      run: |
        ./sun/Sun.exe
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: main.exe